"""empty message

Revision ID: 4c28ad34d9df
Revises: 519e526766d4
Create Date: 2025-02-16 21:05:44.111546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c28ad34d9df'
down_revision = '519e526766d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_record_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comments_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'records', ['record_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('exchangelist', schema=None) as batch_op:
        batch_op.drop_constraint('exchangelist_requester_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exchangelist_origin_disc_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exchangelist_target_disc_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'records', ['target_disc_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'records', ['origin_disc_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['requester_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint('records_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sell_list', schema=None) as batch_op:
        batch_op.drop_constraint('sell_list_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sell_list_record_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'records', ['record_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('transactions_record_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('transactions_seller_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('transactions_buyer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['buyer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['seller_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'records', ['record_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('wish_list', schema=None) as batch_op:
        batch_op.drop_constraint('wish_list_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('wish_list_record_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'records', ['record_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('wish_list_record_id_fkey', 'records', ['record_id'], ['id'])
        batch_op.create_foreign_key('wish_list_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transactions_buyer_id_fkey', 'users', ['buyer_id'], ['id'])
        batch_op.create_foreign_key('transactions_seller_id_fkey', 'users', ['seller_id'], ['id'])
        batch_op.create_foreign_key('transactions_record_id_fkey', 'records', ['record_id'], ['id'])

    with op.batch_alter_table('sell_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sell_list_record_id_fkey', 'records', ['record_id'], ['id'])
        batch_op.create_foreign_key('sell_list_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('records_owner_id_fkey', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('exchangelist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exchangelist_target_disc_id_fkey', 'records', ['target_disc_id'], ['id'])
        batch_op.create_foreign_key('exchangelist_origin_disc_id_fkey', 'records', ['origin_disc_id'], ['id'])
        batch_op.create_foreign_key('exchangelist_requester_id_fkey', 'users', ['requester_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('comments_record_id_fkey', 'records', ['record_id'], ['id'])

    # ### end Alembic commands ###
