"""empty message

Revision ID: 5193beaa6e85
Revises: d7471db98036
Create Date: 2025-01-24 12:47:47.946406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5193beaa6e85'
down_revision = 'd7471db98036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sell_list', schema=None) as batch_op:
        batch_op.drop_constraint('sell_list_record_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'records', ['record_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sell_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sell_list_record_id_fkey', 'records', ['record_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
