"""empty message

Revision ID: 519e526766d4
Revises: 56abb5fde3ba
Create Date: 2025-02-14 17:41:05.516556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519e526766d4'
down_revision = '56abb5fde3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchangelist', schema=None) as batch_op:
        batch_op.alter_column('origin_disc_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('target_disc_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchangelist', schema=None) as batch_op:
        batch_op.alter_column('target_disc_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('origin_disc_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
