"""empty message

Revision ID: 56abb5fde3ba
Revises: fc8a578c26ef
Create Date: 2025-02-14 17:38:00.871609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56abb5fde3ba'
down_revision = 'fc8a578c26ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchangelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('origin_disc_id', sa.Integer(), nullable=False),
    sa.Column('target_disc_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['origin_disc_id'], ['records.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_disc_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exchanges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('origin_disc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_disc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['origin_disc_id'], ['records.id'], name='exchanges_origin_disc_id_fkey'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name='exchanges_requester_id_fkey'),
    sa.ForeignKeyConstraint(['target_disc_id'], ['records.id'], name='exchanges_target_disc_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exchanges_pkey')
    )
    op.drop_table('exchangelist')
    # ### end Alembic commands ###
