"""empty message

Revision ID: 70ec61f92361
Revises: 90d2a5f0ca97
Create Date: 2025-01-22 15:23:47.154812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ec61f92361'
down_revision = '90d2a5f0ca97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sell_list', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_sell_list', ['user_id', 'record_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    with op.batch_alter_table('wish_list', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_wish_list', ['user_id', 'record_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_list', schema=None) as batch_op:
        batch_op.drop_constraint('unique_wish_list', type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint('users_email_key', ['email'])

    with op.batch_alter_table('sell_list', schema=None) as batch_op:
        batch_op.drop_constraint('unique_sell_list', type_='unique')

    # ### end Alembic commands ###
