"""empty message

Revision ID: 90d2a5f0ca97
Revises: 
Create Date: 2025-01-22 15:11:25.671850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d2a5f0ca97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], name='collections_record_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='collections_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collections_pkey')
    )
    # ### end Alembic commands ###
