"""empty message

Revision ID: deb982c12833
Revises: 
Create Date: 2025-01-22 17:59:24.042341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb982c12833'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections')
    with op.batch_alter_table('sell_list', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_sell_list', ['user_id', 'record_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    with op.batch_alter_table('wish_list', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_wish_list', ['user_id', 'record_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_list', schema=None) as batch_op:
        batch_op.drop_constraint('unique_wish_list', type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint('users_email_key', ['email'])

    with op.batch_alter_table('sell_list', schema=None) as batch_op:
        batch_op.drop_constraint('unique_sell_list', type_='unique')

    op.create_table('collections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], name='collections_record_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='collections_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collections_pkey')
    )
    # ### end Alembic commands ###
